#ifdef MIA_OPTION_UNITYBUILD

#include "box.c"
#include "common.c"
#include "program.c"
#include "proj.c"
#include "quad.c"
#include "RBuffer.c"
#include "RBufferBox.c"
#include "RBufferQuad.c"
#include "RCam.c"
#include "RObj.c"
#include "RObjBox.c"
#include "RObjGroup.c"
#include "RObjQuad.c"
#include "RObjText.c"
#include "RProgram.c"
#include "RShader.c"
#include "RShaderBox.c"
#include "RShaderBoxIndexed.c"
#include "RShaderQuad.c"
#include "RShaderQuadChannelMerge.c"
#include "RShaderQuadDab.c"
#include "RShaderQuadKernel.c"
#include "RShaderQuadMerge.c"
#include "RShaderQuadOp.c"
#include "RTex.c"
#include "RTex_blit.c"
#include "RTex_channel.c"
#include "RTex_color.c"
#include "RTex_draw.c"
#include "RTex_imgproc.c"
#include "RTex_math.c"
#include "RTex_text.c"
#include "tex.c"
#include "textlayout.c"

#endif
typedef int avoid_empty_translation_unit;
